services:
  mdnsd:
    container_name: mdnsd
    environment:
      MDNSD_DOCKER_NETWORKS: 'traefik-proxy'
      MDNSD_HOST_INTERFACES: 'enp6s0'
    image: kjkent/mdnsd
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
